config/routes.rb
Rails.application.routes.draw do
  root to: "app_requests#index"
  
  resources :sessions, :only => [:create]
  resources :app_requests, :only => [:index, :show]
  resources :app_controllers, :only => [:index]
  resources :api_keys, :only => [:index]

  namespace :api do
    resources :app_requests, :only => [:create]
  end
end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  def self.generate
    api_key = ApiKey.new
    api_key.key_text = SecureRandom.hex(20)
    api_key.save
    api_key
  end
end

app/models/app_request.rb
class AppRequest < ActiveRecord::Base

  def self.slowest(api_key, num=20)
    AppRequest.where(api_key: api_key).limit(num).order('request_time_in_milliseconds desc')
  end

  def self.by_controller(api_key, controller, action)
    AppRequest.where(api_key: api_key)
              .where(controller: controller)
              .where(action: action)
              .order('created_at desc')
              .limit(10)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/api/app_requests_controller.rb
class Api::AppRequestsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    json = JSON.parse(request.body.read)
    app_request = AppRequest.new
    app_request.api_key                       = request.headers["X-THIRTYSIX-API-KEY"]
    app_request.request_id                    = json["request_id"]
    app_request.request_time_in_milliseconds  = json["request_time_in_milliseconds"]
    app_request.controller                    = json["controller"]
    app_request.action                        = json["action"]
    app_request.query_parameters              = json["query_parameters"]
    app_request.memory_in_mb                  = json["memory_in_mb"]
    app_request.objects                       = json["objects"]
    app_request.classes                       = json["classes"]
    app_request.modules                       = json["modules"]
    app_request.floats                        = json["floats"]
    app_request.strings                       = json["strings"]
    app_request.regexps                       = json["regexps"]
    app_request.arrays                        = json["arrays"]
    app_request.hashes                        = json["hashes"]
    app_request.structs                       = json["structs"]
    app_request.files                         = json["files"]
    app_request.memory_in_mb                  = json["memory_in_mb"]
    
    if ApiKey.where(:key_text => app_request.api_key).first.present?
      app_request.save
    else
      Rails.logger.info("Dropping request with invalid api_key [#{app_request.api_key}]")
    end
    
    head :ok
  end
end

app/controllers/api_keys_controller.rb
class ApiKeysController < ApplicationController
  def index
    @api_keys = ApiKey.all
  end
end

app/controllers/app_controllers_controller.rb
class AppControllersController < ApplicationController
  def index
    @app_requests = AppRequest.by_controller(session[:api_key], params[:app_controller], params[:app_action])
  end
end

app/controllers/app_requests_controller.rb
class AppRequestsController < ApplicationController
  def index
    @slowest_requests = AppRequest.slowest(session[:api_key])
  end

  def show
    @app_request = AppRequest.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:api_key] = params[:api_key]
    redirect_to app_requests_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/api_keys/index.html.haml
.content
  .row
    .col-md-12
      .box.box-info
        .box-header
          %h3 API Keys

        .box-body
          %table.table
            %tr
              %th Key
              %th Created At
            - @api_keys.each do |api_key|
              %tr
                %td=api_key.key_text
                %td=I18n.l(api_key.created_at)

app/views/app_controllers/index.html.haml
.content
  .row
    .col-md-12
      .box.box-info
        .box-header
          %h3 Recent Requests for #{params[:app_controller]}
        .box-body
          %table.table
            %tr
              %th ID
              %th Controller
              %th Action
              %th.text-right Time (ms)
              %th.text-right Requested At
            - @app_requests.each do |app_request|
              %tr
                %td=link_to app_request.id, app_request_path(app_request)
                %td=app_request.controller
                %td=app_request.action
                %td.text-right=app_request.request_time_in_milliseconds
                %td.text-right=l app_request.created_at

app/views/app_requests/index.html.haml
.content
  .row
    .col-md-12
      .box.box-info
        .box-header
          %h3 Slowest Requests
        .box-body
          -if @slowest_requests.empty?
            %p This API Key has no requests associated with it
          -else
            %table.table
              %tr
                %th ID
                %th Controller
                %th Action
                %th.text-right Time (ms)
                %th.text-right Strings
              - @slowest_requests.each do |app_request|
                %tr
                  %td=link_to app_request.id, app_request_path(app_request)
                  %td=link_to app_request.controller, app_controllers_path(:app_controller => app_request.controller, :app_action => app_request.action)
                  %td=app_request.action
                  %td.text-right=app_request.request_time_in_milliseconds
                  %td.text-right=app_request.strings

app/views/app_requests/show.html.haml
.content
  .row
    .col-md-12
      .box.box-info
        .box-header
          %h3 App Request
        .box-body
          %table.table
            %tr
              %td.pull-right ID
              %td=@app_request.id
            %tr
              %td.pull-right Controller
              %td=@app_request.controller
            %tr
              %td.pull-right Action
              %td=@app_request.action
            %tr
              %td.pull-right Requested At
              %td=l @app_request.created_at
            %tr
              %td.pull-right Request Time (ms)
              %td=@app_request.request_time_in_milliseconds
            %tr
              %td.pull-right Params
              %td=@app_request.query_parameters
            %tr
              %td.pull-right Objects
              %td=@app_request.objects
            %tr
              %td.pull-right Classes
              %td=@app_request.classes
            %tr
              %td.pull-right Modules
              %td=@app_request.modules
            %tr
              %td.pull-right Floats
              %td=@app_request.floats
            %tr
              %td.pull-right Strings
              %td=@app_request.strings
            %tr
              %td.pull-right RegExps
              %td=@app_request.regexps
            %tr
              %td.pull-right Hashes
              %td=@app_request.hashes
            %tr
              %td.pull-right Structs
              %td=@app_request.structs
            %tr
              %td.pull-right Arrays
              %td=@app_request.arrays
            %tr
              %td.pull-right Files
              %td=@app_request.files

app/views/layouts/application.html.haml
%html
  %head
    %title Thirtysix
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
%body.fixed.skin-blue-light
  .wrapper
    = render 'layouts/navigation/layout'
    .content-wrapper
      = yield
    = render 'layouts/navigation/footer'

app/views/layouts/navigation/_header.html.haml
%header.main-header
  %a.logo{:href=>"/"} Thirtysix
  %nav.navbar.navbar-static-top
    .navbar-custom-menu
      %ul.nav.navbar-nav{:style => "color: white; margin-top: 15px; margin-right: 5px;"}
        %li.user.user-menu
          %span
            -if session[:api_key].present?
              =session[:api_key]
            -else
              No API Key

app/views/layouts/navigation/_layout.html.haml
= render "layouts/navigation/header"
= render "layouts/navigation/sidebar"

app/views/layouts/navigation/_sidebar.html.haml
.main-sidebar
  .sidebar
    =form_tag(sessions_path, :class => "sidebar-form") do
      .input-group
        %input.form-control{:name => "api_key", :placeholder => "Enter API Key"}
          %span.input-group-btn
            %button#search-btn.btn.btn-flat{:name=>"search", :type=>"submit"}
              %i.fa.fa-search
    .sidebar-menu.tree
      %li
        %a{:href=>"/app_requests"}
          %i.fa.fa-book
          %span SLOW REQUESTS
      %li
        %a{:href=>"/api_keys"}
          %i.fa.fa-book
          %span API KEYS